Back out multi-platform Docker CI
GitHub Actions gives this:

    ERROR: docker exporter does not currently support exporting manifest lists

Probably the `docker push` logic needs to be changed so it's not a
separate step.

This needs additional investigation.